language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - flake8 .
  - coverage run test_gan.py
after_success:
  - ./getaltname.py google.com
  - ./getaltname.py google.com -m
  - ./getaltname.py starbucks.com -s 10
  - ./getaltname.py facebook.com -f json
  - ./getaltname.py microsoft.com -o micro_domains.out -f json
after_script:
  - coveralls
