language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - flake8 .
  - coverage run test_gan.py
after_success:
  - ./getaltname.py google.com
  - ./getaltname.py google.com -m
  - ./getaltname.py google.com -f json -o data.out -q
  - ./getaltname.py starbucks.com -s 10
  - ./getaltname.py facebook.com -f json
  - ./getaltname.py microsoft.com -o data.out -f json -q
  - ./getaltname.py test_nmap.xml
  - ./getaltname.py test_nmap.xml -o data.out -q
  - ./getaltname.py test_nmap.xml -f json
  - ./getaltname.py test_nmap.xml -f json -q
after_script:
  - coveralls
